<a href="https://colab.research.google.com/github/Dipendra-Pal/KNN/blob/main/KNN_Multi_Class_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from collections import Counter
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("multiclass_knn_10000.csv")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Separate features and target
X = df[['sepal_length', 'sepal_width', 'petal_length']].values
y = df['class'].values

In [ ]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)


In [ ]:
# Euclidean distance function
def euclidean_distance(a, b):
    return np.sqrt(np.sum((a - b) ** 2))


In [ ]:
# Predict one sample
def predict(X_train, y_train, x_test, k):
    distances = [(euclidean_distance(x_train, x_test), label) for x_train, label in zip(X_train, y_train)]
    distances.sort(key=lambda x: x[0])
    k_nearest_labels = [label for (_, label) in distances[:k]]
    return Counter(k_nearest_labels).most_common(1)[0][0]

In [ ]:
# Predict for all test data
def knn_predict(X_train, y_train, X_test, k):
    return [predict(X_train, y_train, x, k) for x in X_test]

In [ ]:
# Run the classifier
k = 5
y_pred = knn_predict(X_train, y_train, X_test, k)


In [ ]:
# Accuracy
accuracy = np.sum(y_pred == y_test) / len(y_test)
print(f"Accuracy on test set: {accuracy * 100:.2f}%")

Accuracy on test set: 91.85%


In [ ]:
# Show results
print("Test Features:")
print(X_test)
print("True Labels:", y_test)
print("Predicted Labels:", y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Test Features:
[[6.70350533 3.014615   4.57327232]
 [4.97839696 3.59828589 1.52298893]
 [4.51775503 3.69556311 1.48833251]
 ...
 [4.69615066 3.39612073 1.40322496]
 [6.86544289 3.13578721 4.80730554]
 [5.34196357 3.61335435 1.35131794]]
True Labels: [1 0 0 ... 0 1 0]
Predicted Labels: [np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(1), np.int64(2), np.int64(0), np.int64(0), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(0), np.int64(0), np.int64(2), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(2), np.int64(1), np.int64(2), np.int64(2), np.int64(0), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(0), np.int64(0), np.int64(2), np.int64(0), np.int64(1), np.int64(0), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(1), np.int64(2), np.int64(0), np.int64(1), np.int64(2), np.int64(0), np.int64(2), np.int64(2), np.int64(0), np.int64(1), np.int64(1), np.int64(2)